modLoader="javafml"
loaderVersion="${forge_range}"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="scabbard"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits="${mod_credits}"
description='''${mod_description}'''
logoFile="assets/logo.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION"

[[dependencies.scabbard]]
modId="minecraft"
mandatory=true
versionRange="${mc_range}"
ordering="NONE"
side="BOTH"

[[dependencies.scabbard]]
modId="forge"
mandatory=true
versionRange="${forge_range}"
ordering="NONE"
side="BOTH"